### ISSUE TITLE
Rename "checks" to "events"

### ISSUE THREAD

**Issue by susam** [cloudmarker/cloudmarker#48]
This is a discussion. Right now an example configuration looks like this:

```
audits:
  mockaudit:
    clouds:
      - mockcloud
    stores:
      - filestore
    checks:
      - mockcheck
    alerts:
      - filestore
```

We talk about these plugins in this manner:

- The cloud plugins generate cloud records.
- The store plugins store the cloud records.
- The check plugins generate event records.
- the alert plugins alert on the event records.

I think two separate terms "check" and "event" are superfluous and unnecessary. The word "event" is an industry standard, so I propose we settle only on a single word "event" here. So my proposal is a configuration like this:

```
audits:
  mockaudit:
    clouds:
      - mockcloud
    stores:
      - filestore
    events:
      - mockevent
    alerts:
      - filestore
```

We would now talk about the plugins in this manner:

- The cloud plugins generate cloud records.
- The store plugins store the cloud records.
- The event plugins generate event records.
- the alert plugins alert on the event records.

Let us know what you think.
